
























CREATE TABLE ORDERS 
(
      ORDER_NUMBER NUMERIC  NOT NULL,
      PARTY_NAME VARCHAR ,
      ACCOUNT_NUMBER VARCHAR ,
      FLOW_STATUS_CODE VARCHAR ,
      ORDERED_DATE VARCHAR ,
      CUST_PO_NUMBER VARCHAR ,
      TOTAL_ORDERED_VALUE NUMERIC ,
      FULFILLMENT_DATE VARCHAR ,
    CONSTRAINT ORDERS_PK PRIMARY KEY(ORDER_NUMBER)
);
CREATE TABLE RESULT 
(
      LOCATION_CODE VARCHAR  NOT NULL,
      LOCATION_FULL_NAME VARCHAR ,
    CONSTRAINT RESULT_PK PRIMARY KEY(LOCATION_CODE)
);


CREATE TABLE ALL_ORDERS 
(
      ORDER_NUMBER NUMERIC  NOT NULL,
      PARTY_NAME VARCHAR ,
      ACCOUNT_NUMBER VARCHAR ,
      FLOW_STATUS_CODE VARCHAR ,
      ORDERED_DATE VARCHAR ,
      CUST_PO_NUMBER VARCHAR ,
      TOTAL_ORDERED_VALUE NUMERIC ,
      FULFILLMENT_DATE VARCHAR ,
    CONSTRAINT ALL_ORDERS_PK PRIMARY KEY(ORDER_NUMBER)
);

CREATE TABLE DATA_SYNCH_ACTIONS 
(
      ID NUMERIC NOT NULL,
      SERVICE_CLASS_NAME VARCHAR NOT NULL,
      ENTITY_CLASS_NAME VARCHAR NOT NULL,
      JSON_PAYLOAD VARCHAR ,
      ACTION VARCHAR NOT NULL,
      DATE_CREATED DATE NOT NULL,
      DATE_LAST_SYNCH DATE NOT NULL,
      LAST_SYNCH_ERROR VARCHAR,
      CUSTOM_METHOD_NAME VARCHAR,
    CONSTRAINT DSA_PK PRIMARY KEY(SERVICE_CLASS_NAME ,ID)
);

CREATE TABLE WEB_SERVICE_CALL 
(
      ID NUMERIC  NOT NULL,
      CONNECTION VARCHAR ,
      REQUEST VARCHAR ,
      METHOD VARCHAR ,
      REQUEST_HEADERS VARCHAR ,
      DURATION NUMERIC ,
      REQUEST_PAYLOAD VARCHAR ,
      RESPONSE_PAYLOAD VARCHAR ,
      ERROR_MESSAGE VARCHAR ,
      TIMESTAMP DATE ,
    CONSTRAINT WEB_SERVICE_CALL_PK PRIMARY KEY(ID)
);
